build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: builder/java
      dockerfile: Dockerfile.build
      artifacts:
        - /app/target/gs-rest-service-0.1.0.jar 
    production:
      name: example/java
      dockerfile: Dockerfile.production
      depends_on:
        - builder
 