FROM  maven:3-jdk-8-alpine

ENV APPLICATION_DIR /app
RUN mkdir $APPLICATION_DIR
WORKDIR $APPLICATION_DIR

# selectively add the POM file
ADD pom.xml $APPLICATION_DIR

# get all the downloads out of the way
RUN mvn dependency:resolve

# copy the source code
ADD . $APPLICATION_DIR

# package the project
RUN mvn package

CMD java -jar target/gs-rest-service-0.1.0.jar 
